services:
  db:
    image: postgis/postgis:15-3.4
    container_name: solarwind-db
    environment:
      POSTGRES_DB: solarwinddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./Backend
    container_name: solarwind-backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: solarwind-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend